#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

$rootApp = __DIR__;

if (!is_file($rootApp . '/vendor/autoload.php')) {
    $rootApp = dirname(__DIR__, 3);
}

require $rootApp . '/vendor/autoload.php';

use Aramayismirzoyan\SafeMigrations\Console\Bin\ConsoleCommand;
use Illuminate\Contracts\Console\Kernel;
use Minicli\App;
use Minicli\Command\CommandCall;

$app = require $rootApp . '/bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

$app = new App();
$input = new CommandCall($argv);

$command = new ConsoleCommand($app, $input);
$command->run();
exit();