#!/usr/bin/env php
<?php

require './vendor/autoload.php';

use Aramayismirzoyan\SafeMigrations\Expressions\InvalidMethodArgumentException;
use Aramayismirzoyan\SafeMigrations\Expressions\SensitiveMigrationsException;
use Aramayismirzoyan\SafeMigrations\Git\GitCommand;
use Aramayismirzoyan\SafeMigrations\Git\GitQuery;
use Aramayismirzoyan\SafeMigrations\SafeMigration;

$event = getenv('GITHUB_EVENT_NAME');
$branch = $argv[1] ?? 'master';

$eventFile = file_get_contents(getenv('GITHUB_EVENT_PATH'));
$eventData = json_decode($eventFile, true);

$before = $eventData['before'] ?? '';
$after = $eventData['after'] ?? '';

const PHPUNIT_TESTSUITE = true;

$gitCommand = new GitCommand(__DIR__);
$gitQuery = new GitQuery(__DIR__);
$safeMigration = new SafeMigration($gitQuery, $gitCommand);

if ($safeMigration->hasSensitiveMigrationsInActions($event, $before, $after, $branch)) {
    throw new SensitiveMigrationsException('You have sensitive migrations.');
}
